### ISSUE TITLE
compile_time is chef-12 only

### ISSUE THREAD

**Issue by popsikle** [reset/libarchive-cookbook#11]
in the default recipe for chef_gem you use the compile_time option, which is not present in chef 11.  You can make this work under chef 11 by checking if that option exists for chef_gem.

```
chef_gem "libarchive-ruby" do
  version "0.0.3"
  compile_time false if respond_to?(:compile_time)
end
```

**Comment by popsikle** [comment]
nm, just saw the readme where you force chef 12.  on a side note, the above change seems to make this cookbook work fine under chef 11 ;)

**Comment by reset** [comment]
@popsikle the recommended compatibility guard doesn't work with all versions of Chef 11. The 0.4.x series of this cookbook will remain compatible with Chef 11 while the newer 0.5.x and beyond versions will force Chef 12 to avoid any confusion.
