### ISSUE TITLE
0.6.0 not compatible with AWS based instances

### ISSUE THREAD

**Issue by GerbenPapo** [reset/libarchive-cookbook#14]
After 0.6.0 was released, we're receiving errors when extracting archives (during deploy on amazon linux based instances)

LoadError: Could not open library 'archive': archive: cannot open shared object file: No such file or directory.
Could not open library 'libarchive.so': libarchive.so: cannot open shared object file: No such file or directory

When testing on a local Centos VM, I get more or less the same error.
Testing on local Ubuntu VM, all works well (because ubuntu already has libarchive installed out of the box?)

The problem is that I'm using another third party cb (github.com/lusis/chef-kibana) that has an unconstraint depend on libarchive, so 0.6.0 is used, while 0.5.0 is now the only working version on aws.
A way of working around this is install libarchive from source on the machine, before the kibana cookbook is run by chef. This is obviously a suboptimal solution. 

Is this a bug in 0.6.0?

**Comment by reset** [comment]
@GerbenPapo sounds like a bug to me!

Any OS other than Ubuntu is a community addition and isn't used in production by me. If you'd like to submit a PR to fix up convergence on an OS that you're using that'd be great. It'll be a bit before I get to fixing anything which isn't Ubuntu related.

**Comment by GerbenPapo** [comment]
@reset thanks, and done!

**Comment by reset** [comment]
@GerbenPapo appreciate the footwork. This is released to the community site in version 0.6.1.
